id: IB12109A2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:12:09+00:00'
last_modified: '2022-06-08T08:44:21.970871+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4547
  title: གནམ་འབྲུག་སེ་བ་བྱང་ཆུབ་ཆོས་གླིང་དགོན་གྱི་ངོ་སྤྲོད་མདོར་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9BF9:
      image_group_id: I00KG02896
      title: ''
      total_pages: 13
      order: 1
      base_file: 9BF9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
